version: '3'

services:
  api-solid-bg:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=${DOCKER_USER}
      - POSTGRESQL_PASSWORD=${DOCKER_PASS} 
      - POSTGRESQL_DATABASE=${DOCKER_DATA}